### ISSUE TITLE
unble to install module

### ISSUE THREAD

**Issue by nicolasvillatte** [ZigmundKreud/coc#37]
![image](https://github.com/ZigmundKreud/coc/assets/4541671/719cde24-afcd-4d73-b35e-14b2c34b613d)
![image](https://github.com/ZigmundKreud/coc/assets/4541671/a18828d2-0e90-4224-9953-940d2bbb4972)
![image](https://github.com/ZigmundKreud/coc/assets/4541671/a18b1c94-d0d1-4d08-8669-cc0ec4ea47db)

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.dirname (node:path:654:5)
    at PackageInstaller.install (file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/installer.mjs:1:831)
    at async #s (file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:8650)
    at async Module.install (file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/package.mjs:1:7532)
    at async file:///C:/Program%20Files/FoundryVTT/Foundry%20Virtual%20Tabletop/resources/app/dist/packages/views.mjs:1:3657
error @ setup.js:5304

**Comment by Qaw** [comment]
Des détails ?
Quelle application ? Foundry ou node.js ou autre ?
Via l'installation automatique dans Foundry ou autre ?

**Comment by nicolasvillatte** [comment]
Foundry, via installation automatique en indiquant le lien vers le module.json ou à travers ke système.
En réessayant aujourd'hui (uninstall/install), tout fonctionnement correctement.
Case closed donc.

Merci.
